server:
  port: 9999

spring:
  datasource:
    username: root
    password: qq6666774
    url: jdbc:mysql:///xdb
  redis:
    port: 6379
    host: 175.178.16.189
    password: 12345678

logging:
  level:
    com.example: debug

# 配置逻辑删除
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: com.example.x_practice_backend.*.entity
